kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
nodes:
- role: control-plane
  # Kubernetes version
  image: kindest/node:v1.32.1
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
networking:
  apiServerPort: 6443
